# AI Tutor Pedagogical Test Harness Configuration

# API Configuration
apiBaseUrl: http://localhost:8080
apiUsername: demo
apiPassword: demo

# Judge Configuration (LLM-as-judge)
judgeModel: gpt-4o
judgeTemperature: 0.2

# Test Scenarios
scenariosPath: scenarios
scenarioFilter: all

# Reporting
reportsOutputDir: test-reports

# Test Execution
passThreshold: 70.0
maxConcurrentSessions: 3
requestTimeoutMs: 30000

# Rate Limiting (helps avoid OpenAI API quota/rate limit errors)
delayBetweenRequestsMs: 1000    # Delay between consecutive requests (default: 1000ms = 1 req/sec)
maxRetries: 3                   # Maximum number of retries for 429/503 errors
retryBackoffMultiplier: 2.0     # Exponential backoff multiplier (delay = 1000 * multiplier^attempt)
