cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:5174
  allow-credentials: true

logging:
  level:
    ch.obermuhlner.aitutor: DEBUG
    ch.obermuhlner.aitutor.conversation.service.SingleJsonEntityAiChatService: TRACE
    ch.obermuhlner.aitutor.conversation.service.StreamReplyThenJsonEntityAiChatService: TRACE
    ch.obermuhlner.aitutor.tutor.service.ConversationSummarizationService: TRACE

